using System.Security.Cryptography;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Mizrachi.Infrastructure.Security;

/// <summary>
/// Supplies a random, in-memory signing key when <c>Jwt:SigningKey</c> is absent and the
/// environment is Development, so a reviewer who has just cloned the repository can exercise the
/// whole authentication flow before setting anything up (NFR-1.5).
/// </summary>
/// <remarks>
/// This is the only place in the codebase where a signing key has no operator behind it, so the
/// conditions are deliberately narrow. Both must hold, and neither is inferred:
/// <list type="number">
///   <item>the host was started in the Development environment, and</item>
///   <item>no key was configured at all.</item>
/// </list>
/// A key that is configured but too short is not replaced — that is an operator mistake and
/// <see cref="JwtOptionsValidator"/> still stops the host. Outside Development this type does
/// nothing whatsoever, and an absent key fails at startup exactly as before (NFR-1.4).
///
/// The key is generated by <see cref="RandomNumberGenerator"/>, lives only in the
/// <see cref="JwtOptions"/> instance, and is never written to disk and never logged — not at
/// this level, not at any level (NFR-2.3, NFR-2.6). The warning below says a key exists and what
/// that costs; it does not say what the key is.
///
/// Two details are load-bearing:
///
/// It runs as <see cref="IPostConfigureOptions{TOptions}"/>, which
/// <see cref="IOptionsFactory{TOptions}"/> applies after configuration binding and before
/// validation, so <see cref="JwtOptionsValidator"/> sees a key that satisfies it rather than
/// racing it.
///
/// The key is generated once per process and cached, not once per call. <c>ValidateOnStart</c>
/// materialises the options through <see cref="IOptionsMonitor{TOptions}"/> while
/// <see cref="JwtTokenIssuer"/> and the bearer middleware read them through
/// <see cref="IOptions{TOptions}"/>; those are separate caches, so this method runs more than
/// once per process. Generating per call would sign tokens with one key and validate them with
/// another.
/// </remarks>
internal sealed class EphemeralDevelopmentSigningKey : IPostConfigureOptions<JwtOptions>
{
    private readonly bool _isDevelopment;
    private readonly ILogger<EphemeralDevelopmentSigningKey> _logger;
    private readonly Lazy<string> _signingKey;

    private int _warned;

    public EphemeralDevelopmentSigningKey(
        bool isDevelopment,
        ILogger<EphemeralDevelopmentSigningKey> logger)
    {
        _isDevelopment = isDevelopment;
        _logger = logger;

        // Base64 of 32 random bytes: 256 bits of entropy carried by 44 ASCII characters, which is
        // comfortably above the 32-byte floor once UTF-8 encoded.
        _signingKey = new Lazy<string>(
            () => Convert.ToBase64String(
                RandomNumberGenerator.GetBytes(JwtOptions.MinimumSigningKeyBytes)),
            LazyThreadSafetyMode.ExecutionAndPublication);
    }

    public void PostConfigure(string? name, JwtOptions options)
    {
        if (!_isDevelopment || !string.IsNullOrWhiteSpace(options.SigningKey))
        {
            return;
        }

        options.SigningKey = _signingKey.Value;

        // Once per process, however many times the options are materialised. A warning repeated
        // on every cache miss is a warning a developer learns to scroll past.
        if (Interlocked.Exchange(ref _warned, 1) == 0)
        {
            _logger.LogWarning(
                "Jwt:SigningKey is not configured. A random {KeyBits}-bit key was generated in " +
                "memory for this run, because the environment is Development. " +
                "The key is ephemeral: every token issued now stops being accepted the moment " +
                "this process stops, and a second instance of the API will not accept this " +
                "instance's tokens. It is never written to disk and never logged. " +
                "Set a stable key to avoid this: " +
                "dotnet user-secrets set \"Jwt:SigningKey\" \"<value>\" --project src/Mizrachi.Api",
                JwtOptions.MinimumSigningKeyBytes * 8);
        }
    }
}
