<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>22846f68-fc7b-4be3-86ec-5c0c32593beb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mizrachi.Application\Mizrachi.Application.csproj" />
    <ProjectReference Include="..\Mizrachi.Infrastructure\Mizrachi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
